# Generated by Django 5.0.4 on 2024-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
